import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import {ReduxProvider} from '@/Redux/ReduxProvider'
import './globals.css'
import Sidebar from './../components/Sidebar';
import Footer from './../components/Footer';
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import TanstackProvider from './../ReactProvider/reactProvider';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <TanstackProvider>
            <Navbar/>
            <div className="flex">
            <Sidebar/>
            {children}
            </div>
            <Footer />
            </TanstackProvider>
        </ReduxProvider>
        </body>
    </html>
  )
}
